name: Nix CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Run nix flake check
      run: nix flake check

  build-nixos-config:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Build NixOS configuration
      run: nix build .#nixosConfigurations.solderpad.config.system.build.toplevel

  build-home-manager-configs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Build Home Manager configurations
      run: |
        nix build .#homeConfigurations.xidaren2.activationPackage
        nix build .#homeConfigurations.cedar.activationPackage
